commonFiles = main.css
androidFiles = ${commonFiles}\
			   android.css
iosFiles = ${commonFiles}\
		   ios.css
winFiles = ${commonFiles}\
		   win.css
webFiles = ${commonFiles}\
		   		web.css
		   
all:ios android win web
ios:${iosFiles} 
	cat ${iosFiles} > /home/jpginc/YouLose-iphone/www/css/style.css
android:${androidFiles} 
	cat ${androidFiles} > /home/jpginc/YouLose-android/www/css/style.css
win:${winFiles} 
	cat ${winFiles} > /home/jpginc/YouLose-android/www/css/style.css
web:${webFiles} 
	cat ${webFiles} > /home/jpginc/YouLose-web/css/style.css
