all:ios android win standard
ios: 
	cat licence i-index.html > /home/jpginc/YouLose-iphone/www/index.html
android: 
	cat licence a-index.html > /home/jpginc/YouLose-iphone/www/index.html
win: 
	cat licence a-index.html > /home/jpginc/YouLose-iphone/www/index.html
standard:
	cat licence s-index.html > /home/jpginc/YouLose-standard/index.html
