all:ios android win standard
ios: 
	cat licence mobile-index.html > /home/jpginc/YouLose-iphone/www/index.html
android: 
	cat licence mobile-index.html > /home/jpginc/YouLose-iphone/www/index.html
win: 
	cat licence mobile-index.html > /home/jpginc/YouLose-iphone/www/index.html
standard:
	cat licence web-index.html > /home/jpginc/YouLose-standard/index.html
